# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='f',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
