# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='f',
        ),
    ]
