# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20171010_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='title',
            field=models.CharField(blank=True, max_length=10, verbose_name='название'),
        ),
    ]
