# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_like_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='title',
            field=models.CharField(default='лайк', max_length=10, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='рейтинг'),
        ),
    ]
