# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20171011_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='qlikes', to='questions.Like'),
        ),
    ]
